fix snapshot
kiku-h/latteart pull request #39
Opened 2023-05-12 02:31 UTC by nemotoaa

2023-05-12 02:44 UTC, fujiwr requested changes

2023-05-12 02:44 UTC, fujiwr commented on packages/latteart-gui/src/components/molecules/VideoDisplay.vue
> +    if (this.isViewerMode) {
`isViewerMode`ではなく、条件無しで`video.src`に代入する形でおねがいします。

2023-05-12 02:44 UTC, fujiwr commented on packages/latteart-gui/src/components/molecules/VideoDisplay.vue
> +  private isViewerMode = (this as any).$isViewerMode
moleculesなので`isViewerMode`といったLatteArt固有の概念は登場しないようにしてください。

2023-05-12 04:32 UTC, nemotoaa commented on packages/latteart-gui/src/components/molecules/VideoDisplay.vue
> +    if (this.isViewerMode) {
指摘通り、修正致しました。

2023-05-12 04:32 UTC, nemotoaa commented on packages/latteart-gui/src/components/molecules/VideoDisplay.vue
> +  private isViewerMode = (this as any).$isViewerMode
指定通り、修正致しました。

2023-05-15 02:29 UTC, fujiwr approved these changes

2023-05-15 02:30 UTC, merged